/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../../packages/shared/src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        paper: 'rgb(var(--paper-rgb) / <alpha-value>)',
        'paper-2': 'rgb(var(--paper-2-rgb) / <alpha-value>)',
        ink: 'rgb(var(--ink-rgb) / <alpha-value>)',
        'ink-2': 'rgb(var(--ink-2-rgb) / <alpha-value>)',
        'ink-3': 'rgb(var(--ink-3-rgb) / <alpha-value>)',
        line: 'rgb(var(--line-rgb) / <alpha-value>)',
        'line-2': 'rgb(var(--line-2-rgb) / <alpha-value>)',
        pine: 'rgb(var(--pine-rgb) / <alpha-value>)',
        'pine-soft': 'rgb(var(--pine-soft-rgb) / <alpha-value>)',
        'pine-ink': 'rgb(var(--pine-ink-rgb) / <alpha-value>)',
        terra: 'rgb(var(--terra-rgb) / <alpha-value>)',
        'terra-soft': 'rgb(var(--terra-soft-rgb) / <alpha-value>)',
        amber: 'rgb(var(--amber-rgb) / <alpha-value>)',
        'amber-soft': 'rgb(var(--amber-soft-rgb) / <alpha-value>)',
        'amber-ink': 'rgb(var(--amber-ink-rgb) / <alpha-value>)',
        red: 'rgb(var(--red-rgb) / <alpha-value>)',
        'red-soft': 'rgb(var(--red-soft-rgb) / <alpha-value>)',
        primary: 'rgb(var(--pine-rgb) / <alpha-value>)',
        'primary-foreground': 'rgb(253 251 245 / <alpha-value>)',
        secondary: 'rgb(var(--pine-soft-rgb) / <alpha-value>)',
        'secondary-foreground': 'rgb(var(--pine-ink-rgb) / <alpha-value>)',
        background: 'rgb(var(--paper-rgb) / <alpha-value>)',
        foreground: 'rgb(var(--ink-rgb) / <alpha-value>)',
        card: 'rgb(var(--card-rgb) / <alpha-value>)',
        'card-alt': 'rgb(var(--paper-rgb) / <alpha-value>)',
        'card-foreground': 'rgb(var(--ink-rgb) / <alpha-value>)',
        popover: 'rgb(var(--card-rgb) / <alpha-value>)',
        'popover-foreground': 'rgb(var(--ink-rgb) / <alpha-value>)',
        muted: 'rgb(var(--paper-2-rgb) / <alpha-value>)',
        'muted-foreground': 'rgb(var(--ink-2-rgb) / <alpha-value>)',
        accent: 'rgb(var(--amber-soft-rgb) / <alpha-value>)',
        'accent-foreground': 'rgb(var(--amber-ink-rgb) / <alpha-value>)',
        tertiary: 'rgb(var(--terra-soft-rgb) / <alpha-value>)',
        'tertiary-foreground': 'rgb(var(--terra-rgb) / <alpha-value>)',
        success: 'rgb(var(--pine-rgb) / <alpha-value>)',
        'success-foreground': 'rgb(var(--pine-ink-rgb) / <alpha-value>)',
        warning: 'rgb(var(--amber-rgb) / <alpha-value>)',
        'warning-foreground': 'rgb(var(--amber-ink-rgb) / <alpha-value>)',
        info: 'rgb(var(--pine-rgb) / <alpha-value>)',
        'info-foreground': 'rgb(253 251 245 / <alpha-value>)',
        destructive: 'rgb(var(--red-rgb) / <alpha-value>)',
        'destructive-foreground': 'rgb(253 251 245 / <alpha-value>)',
        border: 'rgb(var(--line-rgb) / <alpha-value>)',
        input: 'rgb(var(--line-rgb) / <alpha-value>)',
        ring: 'rgb(var(--pine-rgb) / <alpha-value>)',
        'sidebar-background': 'rgb(var(--paper-2-rgb) / <alpha-value>)',
        'sidebar-foreground': 'rgb(var(--ink-rgb) / <alpha-value>)',
        'sidebar-primary': 'rgb(var(--pine-rgb) / <alpha-value>)',
        'sidebar-primary-foreground': 'rgb(253 251 245 / <alpha-value>)',
        'sidebar-accent': 'rgb(var(--card-rgb) / <alpha-value>)',
        'sidebar-accent-foreground': 'rgb(var(--ink-rgb) / <alpha-value>)',
        'sidebar-border': 'rgb(var(--line-rgb) / <alpha-value>)',
        'sidebar-ring': 'rgb(var(--pine-rgb) / <alpha-value>)',
      },
      borderRadius: {
        DEFAULT: 'var(--radius)',
      },
      boxShadow: {
        soft: 'var(--shadow-soft)',
        card: 'var(--shadow-card)',
        'card-hover': 'var(--shadow-card-hover)',
      },
      spacing: {
        18: '4.5rem',
        88: '22rem',
        128: '32rem',
        144: '36rem',
      },
      maxWidth: {
        1280: '1280px',
      },
      fontFamily: {
        sans: ['Instrument Sans', 'sans-serif'],
        display: ['Fraunces', 'serif'],
        mono: ['IBM Plex Mono', 'monospace'],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'bounce-gentle': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(-2deg)' },
          '75%': { transform: 'rotate(2deg)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.35s ease-out both',
        'bounce-gentle': 'bounce-gentle 2s ease-in-out infinite',
        wiggle: 'wiggle 0.5s ease-in-out',
      },
    },
  },
  plugins: [],
};
